### ISSUE TITLE
Connecting from host machine

### ISSUE THREAD

**Issue by marcioAlmada** [kadishmal/cubrid-cookbook#4]
Hello,

I have proper drivers installed and loaded, but I simply can't connect to 33000 broker port from my host machine using `cubrid:host=10.11.12.13;port=33000;dbname=demodb` and user `dba`

> `PDOException: Could not connect to database (demodb).`

Connecting to database from within the guest VM works fine. Is there any extra configuration I need to do to be able to connect to CUBRID from host machine? Anything like enabling CUBRID remote connections?

**Comment by kadishmal** [comment]
Hi @marcioAlmada! Sorry for the late reply. I haven't been checking my email lately as often as I used to.

Regarding your question, if you're able to connect to the database within VM, means it's running but you have firewall/VM blocking the access from the outside. There are several solutions for this.
1. If you're using [Vagrant](http://www.cubrid.org/wiki_tutorials/entry/create-a-cubrid-database-vm-with-vagrant-and-chef-cookbook-under-5-minutes) to start up your VM, all you need to do is add the [port forwarding rules](http://docs.vagrantup.com/v2/networking/forwarded_ports.html).
2. If you've started up VM directly via VirtualBox/VMware, first you need to make sure your firewall is not blocking external connections. Ubuntu by default doesn't enabled firewall, so you don't have to do anything here. But if you're using CentOS, you need to check your `sudo iptables -L` and make sure CUBRID's ports are open (33000). Then in your VM settings, you can also enable port forwarding so that you can access your DB from your host using `localhost` address.

Let me know if this solves your issue.

**Comment by kadishmal** [comment]
I think this issue is related to your question you've asked at [SO](http://stackoverflow.com/questions/20695730/is-it-possible-to-run-cubrid-on-travis-ci/20753722#20753722). So, closing this ticket. Please feel free to reopen.

**Comment by marcioAlmada** [comment]
Yes, thank you!
